# -*- coding: utf-8 -*-
"""HeathcareAI

Automatically generated by Colab.

"""


import gradio as gr
from groq import Groq
from fpdf import FPDF
import tempfile
import re
import os

# -------------------------------
# GROQ CLIENT
# -------------------------------
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY)
MODEL_NAME = "openai/gpt-oss-120b"
WHISPER_MODEL = "whisper-large-v3-turbo"

# Hardwired to understand Tanglish but reply ONLY in simple English
SYSTEM_PROMPT = (
    "You are a friendly and careful healthcare assistant. "
    "Explain conditions and treatments clearly. "
    "IMPORTANT RULES: "
    "1. The user may ask questions in Tanglish (Tamil written in the English alphabet) or English. You must understand them, but your output MUST be entirely in clear, simple English. "
    "2. Do not use any Tanglish or Tamil in your response. "
    "3. TOOLTIP REQUIREMENT: Whenever you use a complex medical term, you MUST wrap it in an HTML abbr tag with a title attribute containing a simple definition. "
    "Format exactly like this: <abbr title='Simple explanation goes here'>ComplexMedicalTerm</abbr>. Do not use standard markdown links for this. "
    "Never provide a definitive diagnosis."
)

# -------------------------------
# VOICE INPUT
# -------------------------------
def transcribe_audio(audio_path):
    if not audio_path:
        return gr.update(), None
    try:
        with open(audio_path, "rb") as f:
            transcription = client.audio.transcriptions.create(
                file=(audio_path, f.read()),
                model=WHISPER_MODEL,
            )
        return transcription.text, None
    except Exception as e:
        return f"⚠️ Voice transcription error: {type(e).__name__}: {e}", None

# -------------------------------
# PDF EXPORT HELPER
# -------------------------------
def clean_text_for_pdf(text):
    lines = text.split('\n')
    final_lines = []
    in_table = False
    headers = []

    for line in lines:
        if '|' in line and '-' in line and not any(c.isalpha() for c in line):
            continue
        elif '|' in line:
            cells = [c.strip() for c in line.split('|') if c.strip()]
            if not in_table:
                headers = cells
                in_table = True
            else:
                for i, cell in enumerate(cells):
                    head = headers[i] if i < len(headers) else ""
                    if head and cell:
                        final_lines.append(f"- {head}: {cell}")
                    elif cell:
                        final_lines.append(f"- {cell}")
                final_lines.append("")
        else:
            in_table = False
            final_lines.append(line)

    out = '\n'.join(final_lines)
    out = re.sub(r'<abbr title="([^"]+)">([^<]+)</abbr>', r'\2 (\1)', out)
    out = re.sub(r'\*\*(.*?)\*\*', r'\1', out)
    out = out.replace("#", "")
    out = re.sub(r'<[^>]+>', '', out)

    return out.encode('latin-1', 'ignore').decode('latin-1')

def create_pdf(text):
    if not text or text.strip() == "":
        return None

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Treatment Plan Details", ln=True, align='C')
    pdf.ln(5)
    pdf.set_font("Arial", size=12)
    safe_text = clean_text_for_pdf(text)
    pdf.multi_cell(0, 8, txt=safe_text)

    temp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(temp_pdf.name)
    return temp_pdf.name

# -------------------------------
# CORE GENERATION FUNCTION
# -------------------------------
def generate_response(messages, max_tokens=3000):
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            max_completion_tokens=max_tokens,
            temperature=0.7,
            top_p=0.9,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"⚠️ Groq API error: {type(e).__name__}: {e}"

# -------------------------------
# PATIENT CHAT
# -------------------------------
def patient_chat(history_state, user_input):
    if not user_input.strip():
        return history_state, render_chat(history_state), ""

    history_state = history_state + [{"role": "user", "content": user_input}]
    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history_state

    reply = generate_response(messages, max_tokens=3000)
    history_state = history_state + [{"role": "assistant", "content": reply}]

    return history_state, render_chat(history_state), ""

def regenerate_chat(history_state):
    if len(history_state) < 2:
        return history_state, render_chat(history_state)

    if history_state[-1]["role"] == "assistant":
        history_state.pop()

    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history_state
    reply = generate_response(messages, max_tokens=3000)
    history_state = history_state + [{"role": "assistant", "content": reply}]

    return history_state, render_chat(history_state)

def render_chat(history_state):
    lines = []
    for msg in history_state:
        speaker = "**Patient:**" if msg["role"] == "user" else "**AI:**"
        lines.append(f"{speaker} {msg['content']}")
    return "\n\n---\n\n".join(lines)

def clear_chat():
    return [], "", ""

# -------------------------------
# DISEASE PREDICTION
# -------------------------------
def disease_prediction(symptoms):
    if not symptoms.strip():
        return "Please enter some symptoms first."

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            f"Symptoms: {symptoms}\n\n"
            "List the possible conditions these symptoms could point to, "
            "explain each briefly, and end with a short note on when to see a doctor. "
            "Do not give a diagnosis.\n\n"
            "IMPORTANT: End your response with a bold 'Urgency Level:' followed by Low, Medium, or High (See Doctor Now) based on the symptoms."
        )}
    ]
    return generate_response(messages, max_tokens=3000)

def clear_pred():
    return "", ""

# -------------------------------
# TREATMENT PLAN
# -------------------------------
def treatment_plan(condition, age, gender, history, height_cm, weight_kg):
    if not condition.strip():
        return "Please enter a condition first.", None

    bmi_line = ""
    bmi_instruction = ""
    if height_cm and weight_kg and height_cm > 0 and weight_kg > 0:
        bmi = weight_kg / ((height_cm / 100) ** 2)
        bmi_line = f"\nHeight: {height_cm} cm\nWeight: {weight_kg} kg\nBMI: {bmi:.1f}"
        bmi_instruction = " Factor the BMI into the lifestyle advice."

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            f"Condition: {condition}\n"
            f"Age: {age}\n"
            f"Gender: {gender}\n"
            f"Medical History: {history}"
            f"{bmi_line}\n\n"
            "Give a clear treatment overview using a markdown tabular column for the main points. "
            "Then, add some lifestyle advice and warning signs below the table."
            f"{bmi_instruction}"
        )}
    ]
    reply = generate_response(messages, max_tokens=3000)
    return reply, create_pdf(reply)

def toggle_bmi_row(show):
    return gr.update(visible=show)

def clear_plan():
    return "", 30, "Male", "", False, None, None, "", None

# -------------------------------
# CSS UI FIXES
# -------------------------------
CUSTOM_CSS = """
#theme-toggle-row {
    position: fixed;
    top: 10px;
    right: 16px;
    z-index: 1000;
    width: auto !important;
    gap: 6px;
}
#theme-toggle-row button {
    min-width: 44px !important;
    padding: 4px 10px !important;
}

/* ---- Text inputs ---- */
.app-input textarea,
.app-input input[type="text"],
.app-input input[type="number"] {
    border-radius: var(--radius-lg, 20px) !important;
    border: 1px solid var(--input-border-color, var(--border-color-primary)) !important;
    background: var(--input-background-fill) !important;
    padding: 12px 18px !important;
    font-size: 15px !important;
    box-sizing: border-box !important;
}
.app-input textarea:focus,
.app-input input[type="text"]:focus,
.app-input input[type="number"]:focus {
    border-color: var(--button-primary-background-fill) !important;
    box-shadow: 0 0 0 3px var(--button-primary-background-fill-hover, var(--button-primary-background-fill)) !important;
    outline: none !important;
}

.app-input textarea {
    min-height: 52px !important;
    max-height: 52px !important;
    height: 52px !important;
    resize: none !important;
    margin: 0 !important;
}

/* ---- Mic button ---- */
.clean-mic {
    border-radius: var(--radius-lg, 20px) !important;
    border: 1px solid var(--input-border-color, var(--border-color-primary)) !important;
    background: var(--input-background-fill) !important;
    min-height: 52px !important;
    max-height: 52px !important;
    height: 52px !important;
    padding: 0 !important;
    margin: 0 !important;
    box-sizing: border-box !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    box-shadow: none !important;
}

.clean-mic:hover {
    border-color: var(--button-primary-background-fill) !important;
}

.clean-mic button {
    height: 100% !important;
    width: 100% !important;
    border: none !important;
    background: transparent !important;
}

.clean-mic button[aria-label="Record"] {
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
}
.clean-mic button[aria-label="Record"] span {
    display: none !important;
}
.clean-mic button[aria-label="Record"]::after {
    content: "Speak" !important;
    color: var(--body-text-color) !important;
    font-size: 14px !important;
    margin-left: 8px !important;
    font-weight: 500 !important;
}

.clean-mic select,
.clean-mic button[aria-label="Clear"],
.clean-mic button[aria-label="Trim"],
.clean-mic button[aria-label="Undo trim"] {
    display: none !important;
}
"""

LIGHT_JS = """
function() {
    document.documentElement.classList.remove('dark');
    document.body.classList.remove('dark');
    const app = document.querySelector('gradio-app');
    if (app) app.classList.remove('dark');
}
"""

DARK_JS = """
function() {
    document.documentElement.classList.add('dark');
    document.body.classList.add('dark');
    const app = document.querySelector('gradio-app');
    if (app) app.classList.add('dark');
}
"""

# -------------------------------
# GRADIO UI
# -------------------------------
with gr.Blocks(theme=gr.themes.Soft(), css=CUSTOM_CSS) as app:
    with gr.Row(elem_id="theme-toggle-row"):
        light_btn = gr.Button("☀️", size="sm", scale=0)
        dark_btn = gr.Button("🌙", size="sm", scale=0)

    gr.Markdown("# 🩺 HealthCare AI Assistant")
    gr.Markdown("⚠️ Informational only. Always consult a doctor.")

    with gr.Tabs():
        # --- TAB 1: CHAT ---
        with gr.TabItem("Chat"):
            chat_state = gr.State([])
            chat_display = gr.Markdown()

            with gr.Row(equal_height=True):
                user_input = gr.Textbox(
                    scale=8,
                    show_label=False,
                    placeholder="Type your message...",
                    container=False,
                    elem_classes=["app-input"]
                )
                mic_chat = gr.Audio(
                    sources=["microphone"],
                    type="filepath",
                    show_label=False,
                    container=False,
                    waveform_options=gr.WaveformOptions(show_recording_waveform=False),
                    scale=1,
                    min_width=80,
                    elem_classes=["clean-mic"]
                )

            with gr.Row():
                send_btn = gr.Button("Send", variant="primary")
                regen_btn = gr.Button("Regenerate")
                clear_btn = gr.Button("Clear Chat")

            mic_chat.stop_recording(transcribe_audio, inputs=[mic_chat], outputs=[user_input, mic_chat])
            send_btn.click(patient_chat, inputs=[chat_state, user_input], outputs=[chat_state, chat_display, user_input])
            regen_btn.click(regenerate_chat, inputs=[chat_state], outputs=[chat_state, chat_display])
            clear_btn.click(clear_chat, outputs=[chat_state, chat_display, user_input])

        # --- TAB 2: DISEASE PREDICTION (Voice Removed) ---
        with gr.TabItem("Disease Prediction"):
            # Simple full-width textbox without the mic
            symptoms = gr.Textbox(
                show_label=False,
                placeholder="Enter symptoms...",
                container=False,
                elem_classes=["app-input"]
            )

            with gr.Row():
                analyze_btn = gr.Button("Analyze", variant="primary")
                clear_pred_btn = gr.Button("Clear")

            pred_output = gr.Markdown()

            analyze_btn.click(disease_prediction, inputs=[symptoms], outputs=[pred_output])
            clear_pred_btn.click(clear_pred, outputs=[symptoms, pred_output])

        # --- TAB 3: TREATMENT PLAN ---
        with gr.TabItem("Treatment Plan"):
            condition = gr.Textbox(show_label=False, placeholder="Enter condition...", container=False, elem_classes=["app-input"])

            with gr.Row():
                age = gr.Number(value=30, show_label=False, container=False, elem_classes=["app-input"])
                gender = gr.Dropdown(["Male", "Female", "Other"], show_label=False, container=False)

            history = gr.Textbox(show_label=False, placeholder="Medical History...", container=False, elem_classes=["app-input"])

            bmi_toggle = gr.Checkbox(label="Add height & weight for BMI-based advice", value=False, container=False)
            with gr.Row(visible=False) as bmi_row:
                # FIXED: container=True is REQUIRED for the labels to render!
                height_cm = gr.Number(label="Height (cm)", value=None, show_label=True, container=True)
                weight_kg = gr.Number(label="Weight (kg)", value=None, show_label=True, container=True)

            with gr.Row():
                gen_plan_btn = gr.Button("Generate Plan", variant="primary")
                clear_plan_btn = gr.Button("Clear")

            plan_output = gr.Markdown()
            plan_pdf = gr.File(label="Download Plan as PDF")

            bmi_toggle.change(toggle_bmi_row, inputs=[bmi_toggle], outputs=[bmi_row])
            gen_plan_btn.click(
                treatment_plan,
                inputs=[condition, age, gender, history, height_cm, weight_kg],
                outputs=[plan_output, plan_pdf]
            )
            clear_plan_btn.click(
                clear_plan,
                outputs=[condition, age, gender, history, bmi_toggle, height_cm, weight_kg, plan_output, plan_pdf]
            )

    light_btn.click(fn=None, inputs=[], outputs=[], js=LIGHT_JS)
    dark_btn.click(fn=None, inputs=[], outputs=[], js=DARK_JS)

app.launch(server_name="0.0.0.0", server_port=10000)
